name: taggie
version: 0.0.1
dependencies:
  angular: "1.0.0"
  web_components: "0.10.0"
  browser: ">=0.10.0+2 <0.11.0"
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"
transformers:
- angular:
    dart_sdk: /usr/lib/dart